integration_name: com.newrelic.mssql

instances:
  - name: mssql-server
    command: all_data
    arguments:
      hostname: 469ewdb07
      username: newrelic
      password: S7bZjAd!Cm4Se#

      # Both port and instance can be omitted to use a default port of 1433
      # port: <Microsoft SQL Server port to connect to. Only needed when instance not specified>

      # Only use instance instead of port if SQL Browser is enabled
      # instance: <The Microsoft SQL Server instance to connect to. Do not supply port if this is specified>

      enable_ssl: true
      trust_server_certificate: true
      # certificate_location: <Location of the SSL Certificate. Do not specify if trust_server_certificate is set to true>
      timeout: 300
      # custom_metrics_query: >-
      #   SELECT
      #     'instance_buffer_pool_size' AS metric_name,
      #     Count_big(*) * (8*1024) AS metric_value,
      #     'gauge' as metric_type,
      #     database_id
      #   FROM sys.dm_os_buffer_descriptors WITH (nolock)
      #   GROUP BY database_id
    labels:
      env: sandbox
      role: mssql
